In [1]:
import pandas as pd 
import numpy as np

### Load the CSV and inspecting it

In [2]:
df = pd.read_csv("messy_students.csv")
print("Shape:", df.shape)
df.head(10)

Shape: (215, 8)

,Student_ID,Full Name,Enrollment_Date,Attendance_Rate,Midterm_Score,Final_Exam_Score,Passed_Prep_Course,Tuition_Paid_USD
0,STU_1010,john DOE,1-Sep-23,89.48,80.0,77,Y,12000
1,STU_1032,emma watson,9/1/2023,NaN,77.0,97,Y,12000
2,STU_1138,Alice johnson,1/9/2023,81.36,52.0,66,no,PENDING
3,STU_1176,Michael Jordan,1-Sep-23,88.73,92.0,73,FALSE,12000
4,STU_1015,BOB MARLEY,1-Sep-23,850.00,49.0,43,FALSE,NaN
5,STU_1111,Sarah-Jane O'Connor,1-Sep-23,93.32,59.0,77,yes,PENDING
6,STU_1168,Alice johnson,1/9/2023,78.94,NaN,40,N,"$12,000"
7,STU_1073,Charlie Brown,NaN,82.30,45.0,50,Yes,12000
8,STU_1014,john DOE,9/1/2023,96.83,85.0,79,TRUE,PENDING
9,STU_1139,Charlie Brown,9/1/2023,96.28,58.0,61,N,"$12,000"

In [3]:
df.dtypes

Student_ID                str
Full Name                 str
Enrollment_Date           str
Attendance_Rate       float64
Midterm_Score         float64
Final_Exam_Score          str
Passed_Prep_Course        str
Tuition_Paid_USD          str
dtype: object

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Student_ID          215 non-null    str
 1   Full Name           215 non-null    str
 2   Enrollment_Date     175 non-null    str
 3   Attendance_Rate     201 non-null    float64
 4   Midterm_Score       200 non-null    float64
 5   Final_Exam_Score    212 non-null    str
 6   Passed_Prep_Course  215 non-null    str
 7   Tuition_Paid_USD    175 non-null    str
dtypes: float64(2), str(6)
memory usage: 21.4 KB

### Duplicates & Missing Values

In [5]:
print("Exact duplicate rows:", df.duplicated().sum())
df[df.duplicated()]

Exact duplicate rows: 6

,Student_ID,Full Name,Enrollment_Date,Attendance_Rate,Midterm_Score,Final_Exam_Score,Passed_Prep_Course,Tuition_Paid_USD
115,STU_1011,Jane Smith,9/1/2023,67.88,97.0,67,FALSE,NaN
120,STU_1010,john DOE,1-Sep-23,89.48,80.0,77,Y,12000
171,STU_1018,Sarah-Jane O'Connor,2023.09.01,96.00,86.0,46,FALSE,12000
193,STU_1013,BOB MARLEY,1-Sep-23,97.95,69.0,76,yes,12000
203,STU_1012,BOB MARLEY,1/9/2023,77.25,93.0,59,yes,NaN
211,STU_1014,john DOE,9/1/2023,96.83,85.0,79,TRUE,PENDING

In [6]:
# Duplicated student ids
print("Duplicate Student_IDs:", df.duplicated(subset=['Student_ID']).sum())
df[df.duplicated(subset=['Student_ID'], keep=False)].sort_values('Student_ID').head(10)

Duplicate Student_IDs: 15

,Student_ID,Full Name,Enrollment_Date,Attendance_Rate,Midterm_Score,Final_Exam_Score,Passed_Prep_Course,Tuition_Paid_USD
0,STU_1010,john DOE,1-Sep-23,89.48,80.0,77,Y,12000
120,STU_1010,john DOE,1-Sep-23,89.48,80.0,77,Y,12000
105,STU_1011,Jane Smith,9/1/2023,67.88,97.0,67,FALSE,NaN
115,STU_1011,Jane Smith,9/1/2023,67.88,97.0,67,FALSE,NaN
71,STU_1012,BOB MARLEY,1/9/2023,77.25,93.0,59,yes,NaN
203,STU_1012,BOB MARLEY,1/9/2023,77.25,93.0,59,yes,NaN
164,STU_1013,BOB MARLEY,1-Sep-23,97.95,69.0,76,yes,12000
193,STU_1013,BOB MARLEY,1-Sep-23,97.95,69.0,76,yes,12000
8,STU_1014,john DOE,9/1/2023,96.83,85.0,79,TRUE,PENDING
211,STU_1014,john DOE,9/1/2023,96.83,85.0,79,TRUE,PENDING

In [7]:
# Checking missing values 
df.isnull().sum()

Student_ID             0
Full Name              0
Enrollment_Date       40
Attendance_Rate       14
Midterm_Score         15
Final_Exam_Score       3
Passed_Prep_Course     0
Tuition_Paid_USD      40
dtype: int64

In [8]:
df.columns

Index(['Student_ID', 'Full Name', 'Enrollment_Date', 'Attendance_Rate',
       'Midterm_Score', 'Final_Exam_Score', 'Passed_Prep_Course',
       'Tuition_Paid_USD'],
      dtype='str')

In [9]:
# checking each rows for the hidden missing values
df["Final_Exam_Score"].unique()

<ArrowStringArray>
[     '77',      '97',      '66',      '73',      '43',      '40',      '50',
      '79',      '61',      '45',      '75',      '57',      '95',      '98',
      '52',      '74',      '46',      '92',      '49',      '53',       ' ',
      '82',      '41',       nan,     '-25',      '93',      '80',     '100',
      '68',      '59',      '76',      '96',      '88',      '71',      '69',
      '62',      '99',      '47',      '65',      '70',      '56',      '51',
      '42',      '87',      '78',      '81',      '44',      '55',      '58',
      '60',      '54',      '94',      '89',      '83',      '84',      '67',
      '64',      '63', 'missing',      '85',      '90',      '91',      '72',
       '-',      '48']
Length: 65, dtype: str

In [10]:
df["Final_Exam_Score"].value_counts().tail(15)

Final_Exam_Score
89         2
91         2
72         2
-          2
97         1
-25        1
93         1
62         1
55         1
94         1
64         1
63         1
missing    1
85         1
48         1
Name: count, dtype: int64

In [11]:
df['Tuition_Paid_USD'].unique()

<ArrowStringArray>
['12000', 'PENDING', nan, '$12,000 ']
Length: 4, dtype: str

In [12]:
df['Tuition_Paid_USD'].value_counts().tail(15)

Tuition_Paid_USD
$12,000     71
12000       67
PENDING     37
Name: count, dtype: int64

In [13]:
# droping the exact duplicated rows
df = df.drop_duplicates()

In [14]:
df.shape

(209, 8)

In [15]:
# remaining duplicated name
print("Duplicate Student_IDs remaining:", df.duplicated(subset=['Student_ID'], keep=False).sum())
df[df.duplicated(subset=['Student_ID'], keep=False)].sort_values('Student_ID')

Duplicate Student_IDs remaining: 18

,Student_ID,Full Name,Enrollment_Date,Attendance_Rate,Midterm_Score,Final_Exam_Score,Passed_Prep_Course,Tuition_Paid_USD
4,STU_1015,BOB MARLEY,1-Sep-23,850.00,49.0,43,FALSE,NaN
79,STU_1015,BOB MARLEY,1-Sep-23,84.93,49.0,43,FALSE,NaN
27,STU_1016,Michael Jordan,2023.09.01,86.54,67.0,79,FALSE,"$12,000"
111,STU_1016,Michael Jordan,2023.09.01,86.54,NaN,79,FALSE,"$12,000"
168,STU_1017,BOB MARLEY,1-Sep-23,64.99,51.0,-,N,PENDING
188,STU_1017,BOB MARLEY,1-Sep-23,64.99,51.0,87,N,PENDING
56,STU_1019,Charlie Brown,1-Sep-23,80.28,73.0,100,Y,PENDING
106,STU_1019,Charlie Brown,1-Sep-23,80.28,NaN,100,Y,PENDING
11,STU_1030,Michael Jordan,2023.09.01,76.24,92.0,75,yes,NaN
47,STU_1030,Michael Jordan,2023.09.01,76.24,92.0,99,yes,NaN
70,STU_1031,Jane Smith,9/1/2023,93.35,86.0,44,FALSE,"$12,000"
180,STU_1031,Jane Smith,9/1/2023,93.35,86.0,98,FALSE,"$12,000"
1,STU_1032,emma watson,9/1/2023,NaN,77.0,97,Y,12000
114,STU_1032,emma watson,9/1/2023,72.15,77.0,50,Y,12000
93,STU_1033,emma watson,NaN,68.41,57.0,96,FALSE,NaN
104,STU_1033,emma watson,NaN,68.41,57.0,40,FALSE,NaN
155,STU_1034,Charlie Brown,1-Sep-23,91.43,60.0,66,FALSE,"$12,000"
206,STU_1034,Charlie Brown,1-Sep-23,91.43,60.0,95,FALSE,"$12,000"

In [16]:
# filling the missing values
# Replace hidden missing-value strings with actual NaN
df['Final_Exam_Score'] = df['Final_Exam_Score'].replace(['missing', 'N/A', ' ', '-'], np.nan)

# Now convert the column to numeric (it's still stored as text/object)
df['Final_Exam_Score'] = pd.to_numeric(df['Final_Exam_Score'])

df['Final_Exam_Score'].isnull().sum()

np.int64(10)

In [17]:
# Attendance can't exceed 100%
df.loc[df['Attendance_Rate'] > 100, 'Attendance_Rate'] = np.nan

# Scores can't be negative
df.loc[df['Final_Exam_Score'] < 0, 'Final_Exam_Score'] = np.nan

# Midterm score of 999 is clearly a data-entry error (max possible should be 100)
df.loc[df['Midterm_Score'] > 100, 'Midterm_Score'] = np.nan

In [18]:
df['Tuition_Paid_USD'] = df['Tuition_Paid_USD'].replace('PENDING', np.nan)
df['Tuition_Paid_USD'] = df['Tuition_Paid_USD'].str.replace('$', '', regex=False)
df['Tuition_Paid_USD'] = df['Tuition_Paid_USD'].str.replace(',', '', regex=False)
df['Tuition_Paid_USD'] = df['Tuition_Paid_USD'].str.strip()

df['Tuition_Paid_USD'] = pd.to_numeric(df['Tuition_Paid_USD'])

df['Tuition_Paid_USD'].unique()

array([12000.,    nan])

In [19]:
df["Enrollment_Date"].unique()

<ArrowStringArray>
['1-Sep-23', '9/1/2023', '1/9/2023', nan, '2023.09.01']
Length: 5, dtype: str

In [20]:
df["Attendance_Rate"].unique()

array([89.48,   nan, 81.36, 88.73, 93.32, 78.94, 82.3 , 96.83, 96.28,
       98.08, 76.24, 67.93, 97.61, 95.42, 98.55, 78.6 , 96.  , 76.86,
       94.42, 97.66, 82.36, 86.6 , 75.32, 67.27, 69.71, 86.54, 86.55,
       95.19, 73.24, 84.45, 75.58, 72.06, 81.53, 79.53, 64.85, 93.62,
       79.08, 88.54, 69.57, 96.32, 83.03, 71.09, 95.68, 79.38, 99.23,
       96.27, 61.61, 98.05, 87.03, 67.67, 93.57, 71.94, 80.28, 68.75,
       77.59, 77.44, 96.78, 90.74, 73.43, 86.46, 77.7 , 95.71, 93.35,
       77.25, 84.27, 66.96, 89.44, 95.72, 70.41, 92.26, 84.93, 74.76,
       65.33, 98.39, 86.75, 81.25, 95.91, 75.17, 77.14, 90.79, 89.39,
       95.98, 78.59, 68.41, 60.78, 78.  , 77.07, 94.67, 72.89, 95.67,
       75.36, 87.89, 86.52, 97.71, 67.88, 97.91, 80.8 , 73.09, 61.78,
       72.15, 93.4 , 97.84, 75.99, 91.99, 89.96, 91.11, 99.37, 92.22,
       61.24, 92.16, 97.16, 87.5 , 71.35, 83.68, 91.75, 82.18, 98.29,
       87.37, 90.21, 80.45, 83.15, 63.74, 69.89, 86.35, 78.19, 67.6 ,
       66.11, 61.85, 91.93, 91.85, 69.54, 62.76, 69.39, 72.69, 91.43,
       62.49, 90.07, 92.6 , 82.64, 94.46, 87.47, 97.95, 75.01, 75.55,
       64.99, 84.85, 78.58, 88.97, 66.55, 81.31, 65.9 , 99.36, 76.59,
       72.42, 84.24, 64.58, 95.45, 66.37, 73.05, 62.74, 70.92, 77.67,
       62.08, 64.63, 65.89, 73.5 , 79.43, 71.13, 66.03, 69.38, 95.23,
       77.84, 96.7 , 75.6 , 86.68, 93.22, 68.56, 93.59, 72.44, 63.22])

In [21]:
df["Midterm_Score"].unique()

array([ 80.,  77.,  52.,  92.,  49.,  59.,  nan,  45.,  85.,  58.,  88.,
        63.,  57.,  47.,  56.,  86.,  84.,  96.,  51.,  74.,  87., 100.,
        67.,  69.,  43.,  70.,  82.,  83.,  60.,  93.,  68.,  40.,  99.,
        98.,  73.,  75.,  46.,  71.,  78.,  94.,  41.,  95.,  66.,  89.,
        54.,  76.,  55.,  61.,  79.,  97.,  48.,  53.,  81.,  91.,  44.,
        90.,  64.,  65.,  62.,  42.])

In [22]:
df["Final_Exam_Score"].unique()

array([ 77.,  97.,  66.,  73.,  43.,  40.,  50.,  79.,  61.,  45.,  75.,
        57.,  95.,  98.,  52.,  74.,  46.,  92.,  49.,  53.,  nan,  82.,
        41.,  93.,  80., 100.,  68.,  59.,  76.,  96.,  88.,  71.,  69.,
        62.,  99.,  47.,  65.,  70.,  56.,  51.,  42.,  87.,  78.,  81.,
        44.,  55.,  58.,  60.,  54.,  94.,  89.,  83.,  84.,  67.,  64.,
        63.,  85.,  90.,  91.,  72.,  48.])

In [23]:
df["Tuition_Paid_USD"].unique()

array([12000.,    nan])

In [24]:
print(df.isnull().sum())
print(df.describe())

Student_ID             0
Full Name              0
Enrollment_Date       40
Attendance_Rate       15
Midterm_Score         16
Final_Exam_Score      11
Passed_Prep_Course     0
Tuition_Paid_USD      74
dtype: int64
       Attendance_Rate  Midterm_Score  Final_Exam_Score  Tuition_Paid_USD
count       194.000000     193.000000        198.000000             135.0
mean         81.923918      69.782383         70.449495           12000.0
std          11.228413      16.365433         17.455236               0.0
min          60.780000      40.000000         40.000000           12000.0
25%          72.502500      57.000000         56.250000           12000.0
50%          82.330000      70.000000         70.500000           12000.0
75%          92.117500      84.000000         84.000000           12000.0
max          99.370000     100.000000        100.000000           12000.0

In [25]:
# Count missing values per row
df['missing_count'] = df.isnull().sum(axis=1)

# Sort so the most complete row (fewest missing values) comes first within each Student_ID group
df = df.sort_values(['Student_ID', 'missing_count'])

# Keep only the first row per Student_ID (i.e. the most complete one)
df = df.drop_duplicates(subset=['Student_ID'], keep='first')

# Drop the helper column, we don't need it anymore
df = df.drop(columns=['missing_count'])

df.shape

(200, 8)

In [26]:
df.duplicated(subset=['Student_ID']).sum()

np.int64(0)

In [27]:
df.isnull().sum()

Student_ID             0
Full Name              0
Enrollment_Date       39
Attendance_Rate       13
Midterm_Score         14
Final_Exam_Score      10
Passed_Prep_Course     0
Tuition_Paid_USD      69
dtype: int64

In [28]:
# filling the missing values
df['Attendance_Rate'] = df['Attendance_Rate'].fillna(df['Attendance_Rate'].median())
df['Midterm_Score'] = df['Midterm_Score'].fillna(df['Midterm_Score'].median())
df['Final_Exam_Score'] = df['Final_Exam_Score'].fillna(df['Final_Exam_Score'].median())

In [29]:
df['Payment_Status'] = np.where(df['Tuition_Paid_USD'].isnull(), 'Pending', 'Paid')
df['Payment_Status'].value_counts()

Payment_Status
Paid       131
Pending     69
Name: count, dtype: int64

In [30]:

df.isnull().sum()

Student_ID             0
Full Name              0
Enrollment_Date       39
Attendance_Rate        0
Midterm_Score          0
Final_Exam_Score       0
Passed_Prep_Course     0
Tuition_Paid_USD      69
Payment_Status         0
dtype: int64

In [31]:
# leaving the enrollment date as it is not in proper format and the tuition_paid_usd as we have already created a new payment_status columns equiavalent to this columns

In [32]:
# Standardize Enrollment_Date
df['Enrollment_Date'].unique()

<ArrowStringArray>
['9/1/2023', nan, '1/9/2023', '1-Sep-23', '2023.09.01']
Length: 5, dtype: str

In [33]:

# df['Enrollment_Date'] = pd.to_datetime(df['Enrollment_Date'], errors='coerce')
# df['Enrollment_Date'].head(10)
# # errors='coerce' tells pandas: "if you can't parse a value, just turn it into NaT" (pandas' version of NaN for dates) instead of crashing.

In [34]:
# df['Enrollment_Date'].isnull().sum()

In [35]:
df["Enrollment_Date"] = df["Enrollment_Date"].fillna("2023-09-01")

In [36]:
df["Enrollment_Date"] = df["Enrollment_Date"].replace("9/1/2023", "2023-09-01")

In [37]:
df["Enrollment_Date"].unique()

<ArrowStringArray>
['2023-09-01', '1/9/2023', '1-Sep-23', '2023.09.01']
Length: 4, dtype: str

In [38]:
df["Enrollment_Date"] = df["Enrollment_Date"].replace("1/9/2023", "2023-09-01")

In [39]:
df["Enrollment_Date"] = df["Enrollment_Date"].replace("1-Sep-23", "2023-09-01")

In [40]:
df["Enrollment_Date"] = df["Enrollment_Date"].replace("2023.09.01", "2023-09-01")

In [41]:
df["Enrollment_Date"].unique()

<ArrowStringArray>
['2023-09-01']
Length: 1, dtype: str

In [42]:

df['Enrollment_Date'] = pd.to_datetime(df['Enrollment_Date'])

In [43]:
df.dtypes

Student_ID                       str
Full Name                        str
Enrollment_Date       datetime64[us]
Attendance_Rate              float64
Midterm_Score                float64
Final_Exam_Score             float64
Passed_Prep_Course               str
Tuition_Paid_USD             float64
Payment_Status                   str
dtype: object

In [44]:
df.isnull().sum()

Student_ID             0
Full Name              0
Enrollment_Date        0
Attendance_Rate        0
Midterm_Score          0
Final_Exam_Score       0
Passed_Prep_Course     0
Tuition_Paid_USD      69
Payment_Status         0
dtype: int64

In [45]:
# formatting full name 
df['Full Name'] = df['Full Name'].str.strip().str.title()
df['Full Name'].unique()

<ArrowStringArray>
[         'Jane Smith',            'John Doe',       'Charlie Brown',
          'Bob Marley',       'Alice Johnson',      'Michael Jordan',
 'Sarah-Jane O'Connor',         'Emma Watson']
Length: 8, dtype: str

In [46]:
df['Passed_Prep_Course'].unique()

<ArrowStringArray>
['N', 'Y', 'yes', 'Yes', 'TRUE', 'No', 'FALSE', 'no']
Length: 8, dtype: str

In [71]:
# Standardize the Passed_Prep_Course
yes_values = ['Yes', 'Y', 'yes', 'TRUE']

# Assign 'Yes' if value is in list, otherwise 'No'
df['Passed_Prep_Course'] = np.where(df['Passed_Prep_Course'].isin(yes_values), 'Yes', 'No')

In [48]:
df.info()

<class 'pandas.DataFrame'>
Index: 200 entries, 125 to 152
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Student_ID          200 non-null    str
 1   Full Name           200 non-null    str
 2   Enrollment_Date     200 non-null    datetime64[us]
 3   Attendance_Rate     200 non-null    float64
 4   Midterm_Score       200 non-null    float64
 5   Final_Exam_Score    200 non-null    float64
 6   Passed_Prep_Course  200 non-null    str
 7   Tuition_Paid_USD    131 non-null    float64
 8   Payment_Status      200 non-null    str
dtypes: datetime64[us](1), float64(4), str(4)
memory usage: 21.1 KB

In [49]:
df = df.drop(columns=['Tuition_Paid_USD'])
df.columns

Index(['Student_ID', 'Full Name', 'Enrollment_Date', 'Attendance_Rate',
       'Midterm_Score', 'Final_Exam_Score', 'Passed_Prep_Course',
       'Payment_Status'],
      dtype='str')

In [50]:
df.info()

<class 'pandas.DataFrame'>
Index: 200 entries, 125 to 152
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Student_ID          200 non-null    str
 1   Full Name           200 non-null    str
 2   Enrollment_Date     200 non-null    datetime64[us]
 3   Attendance_Rate     200 non-null    float64
 4   Midterm_Score       200 non-null    float64
 5   Final_Exam_Score    200 non-null    float64
 6   Passed_Prep_Course  200 non-null    str
 7   Payment_Status      200 non-null    str
dtypes: datetime64[us](1), float64(3), str(4)
memory usage: 19.5 KB

In [51]:
# final full check before analysis
print(df.info())
print(df.describe(include = "all"))
print(df.head(10))

<class 'pandas.DataFrame'>
Index: 200 entries, 125 to 152
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Student_ID          200 non-null    str
 1   Full Name           200 non-null    str
 2   Enrollment_Date     200 non-null    datetime64[us]
 3   Attendance_Rate     200 non-null    float64
 4   Midterm_Score       200 non-null    float64
 5   Final_Exam_Score    200 non-null    float64
 6   Passed_Prep_Course  200 non-null    str
 7   Payment_Status      200 non-null    str
dtypes: datetime64[us](1), float64(3), str(4)
memory usage: 19.5 KB
None
       Student_ID   Full Name      Enrollment_Date  Attendance_Rate  \
count         200         200                  200       200.000000
unique        200           8                  NaN              NaN
top      STU_1000  Bob Marley                  NaN              NaN
freq            1          36                  NaN              NaN
mean          NaN         NaN  2023-09-01 00:00:00        82.013400
min           NaN         NaN  2023-09-01 00:00:00        60.780000
25%           NaN         NaN  2023-09-01 00:00:00        73.080000
50%           NaN         NaN  2023-09-01 00:00:00        82.360000
75%           NaN         NaN  2023-09-01 00:00:00        91.870000
max           NaN         NaN  2023-09-01 00:00:00        99.370000
std           NaN         NaN                  NaN        10.887077

        Midterm_Score  Final_Exam_Score Passed_Prep_Course Payment_Status
count      200.000000        200.000000                200            200
unique            NaN               NaN                  8              2
top               NaN               NaN                yes           Paid
freq              NaN               NaN                 31            131
mean        69.880000         69.990000                NaN            NaN
min         40.000000         40.000000                NaN            NaN
25%         57.000000         57.000000                NaN            NaN
50%         70.000000         70.000000                NaN            NaN
75%         82.250000         82.250000                NaN            NaN
max        100.000000        100.000000                NaN            NaN
std         15.782619         16.545047                NaN            NaN
    Student_ID       Full Name Enrollment_Date  Attendance_Rate  \
125   STU_1000      Jane Smith      2023-09-01            99.37
194   STU_1001        John Doe      2023-09-01            64.63
90    STU_1002   Charlie Brown      2023-09-01            95.98
146   STU_1003      Bob Marley      2023-09-01            67.60
113   STU_1004      Bob Marley      2023-09-01            61.78
61    STU_1005   Alice Johnson      2023-09-01            77.44
108   STU_1006      Jane Smith      2023-09-01            80.80
156   STU_1007      Jane Smith      2023-09-01            92.26
163   STU_1008  Michael Jordan      2023-09-01            87.47
13    STU_1009        John Doe      2023-09-01            97.61

     Midterm_Score  Final_Exam_Score Passed_Prep_Course Payment_Status
125           81.0              79.0                  N           Paid
194           61.0              70.0                  Y           Paid
90            40.0              89.0                yes        Pending
146           94.0              73.0                Yes        Pending
113           66.0              64.0               TRUE           Paid
61            92.0              68.0                 No        Pending
108           70.0              98.0                  N        Pending
156           70.0              68.0                 No        Pending
163           67.0              59.0              FALSE           Paid
13            63.0              95.0                 No        Pending

In [52]:
df.sort_index(inplace = True)

#### Selecting Rows & Columns

In [53]:
# selecting a single column
df["Full Name"].head()

0               John Doe
2          Alice Johnson
3         Michael Jordan
5    Sarah-Jane O'Connor
6          Alice Johnson
Name: Full Name, dtype: str

In [54]:
# selecting multiple columns
df[["Full Name", "Midterm_Score", "Final_Exam_Score"]].head()

             Full Name  Midterm_Score  Final_Exam_Score
0             John Doe           80.0              77.0
2        Alice Johnson           52.0              66.0
3       Michael Jordan           92.0              73.0
5  Sarah-Jane O'Connor           59.0              77.0
6        Alice Johnson           70.0              40.0

In [55]:
# .loc — label-based selection (rows by index label, columns by name)
df.loc[1:12, ["Student_ID", "Final_Exam_Score"]]

   Student_ID  Final_Exam_Score
2    STU_1138              66.0
3    STU_1176              73.0
5    STU_1111              77.0
6    STU_1168              40.0
7    STU_1073              50.0
8    STU_1014              79.0
9    STU_1139              61.0
10   STU_1158              45.0
11   STU_1030              75.0
12   STU_1186              57.0

In [56]:
# .iloc — pure position-based selection (ignores index labels, just row order)
df.iloc[1:12, 0:5]

,Student_ID,Full Name,Enrollment_Date,Attendance_Rate,Midterm_Score
2,STU_1138,Alice Johnson,2023-09-01,81.36,52.0
3,STU_1176,Michael Jordan,2023-09-01,88.73,92.0
5,STU_1111,Sarah-Jane O'Connor,2023-09-01,93.32,59.0
6,STU_1168,Alice Johnson,2023-09-01,78.94,70.0
7,STU_1073,Charlie Brown,2023-09-01,82.30,45.0
8,STU_1014,John Doe,2023-09-01,96.83,85.0
9,STU_1139,Charlie Brown,2023-09-01,96.28,58.0
10,STU_1158,John Doe,2023-09-01,98.08,88.0
11,STU_1030,Michael Jordan,2023-09-01,76.24,92.0
12,STU_1186,Jane Smith,2023-09-01,67.93,49.0
13,STU_1009,John Doe,2023-09-01,97.61,63.0

In [57]:
# Selecting a single cell value
df.loc[0, 'Full Name']

'John Doe'

### Filtering

In [58]:
#students with high attendance (above 90%)
high_attendance = df[df['Attendance_Rate'] > 90]
print(len(high_attendance))
high_attendance.head()

59

,Student_ID,Full Name,Enrollment_Date,Attendance_Rate,Midterm_Score,Final_Exam_Score,Passed_Prep_Course,Payment_Status
5,STU_1111,Sarah-Jane O'Connor,2023-09-01,93.32,59.0,77.0,yes,Pending
8,STU_1014,John Doe,2023-09-01,96.83,85.0,79.0,TRUE,Pending
9,STU_1139,Charlie Brown,2023-09-01,96.28,58.0,61.0,N,Paid
10,STU_1158,John Doe,2023-09-01,98.08,88.0,45.0,yes,Pending
13,STU_1009,John Doe,2023-09-01,97.61,63.0,95.0,No,Pending

In [59]:
# high attendance BUT still failing (Final_Exam_Score < 50)
attend_but_fail = df[(df['Attendance_Rate'] > 90) & (df['Final_Exam_Score'] < 50)]
attend_but_fail

,Student_ID,Full Name,Enrollment_Date,Attendance_Rate,Midterm_Score,Final_Exam_Score,Passed_Prep_Course,Payment_Status
10,STU_1158,John Doe,2023-09-01,98.08,88.0,45.0,yes,Pending
17,STU_1018,Sarah-Jane O'Connor,2023-09-01,96.00,86.0,46.0,FALSE,Paid
19,STU_1066,Bob Marley,2023-09-01,94.42,96.0,49.0,no,Paid
37,STU_1135,Alice Johnson,2023-09-01,93.62,58.0,45.0,FALSE,Pending
70,STU_1031,Jane Smith,2023-09-01,93.35,86.0,44.0,FALSE,Paid
88,STU_1113,Charlie Brown,2023-09-01,90.79,54.0,41.0,No,Paid
103,STU_1119,Emma Watson,2023-09-01,97.71,87.0,42.0,FALSE,Paid
128,STU_1070,John Doe,2023-09-01,92.16,73.0,49.0,TRUE,Paid
159,STU_1083,Alice Johnson,2023-09-01,92.60,81.0,47.0,Y,Paid
183,STU_1048,Bob Marley,2023-09-01,98.08,82.0,44.0,TRUE,Paid
208,STU_1188,Bob Marley,2023-09-01,93.22,76.0,48.0,FALSE,Pending

In [61]:
# filtering those who did n't pay tuition fee
pending_payment = df[df['Payment_Status'] == 'Pending']
print(len(pending_payment))
pending_payment.head()

69

,Student_ID,Full Name,Enrollment_Date,Attendance_Rate,Midterm_Score,Final_Exam_Score,Passed_Prep_Course,Payment_Status
2,STU_1138,Alice Johnson,2023-09-01,81.36,52.0,66.0,no,Pending
5,STU_1111,Sarah-Jane O'Connor,2023-09-01,93.32,59.0,77.0,yes,Pending
8,STU_1014,John Doe,2023-09-01,96.83,85.0,79.0,TRUE,Pending
10,STU_1158,John Doe,2023-09-01,98.08,88.0,45.0,yes,Pending
11,STU_1030,Michael Jordan,2023-09-01,76.24,92.0,75.0,yes,Pending

In [72]:
# filtering the student having name John
df[df['Full Name'].str.contains('John ', case=False)]

,Student_ID,Full Name,Enrollment_Date,Attendance_Rate,Midterm_Score,Final_Exam_Score,Passed_Prep_Course,Payment_Status
0,STU_1010,John Doe,2023-09-01,89.48,80.0,77.0,Yes,Paid
8,STU_1014,John Doe,2023-09-01,96.83,85.0,79.0,Yes,Pending
10,STU_1158,John Doe,2023-09-01,98.08,88.0,45.0,Yes,Pending
13,STU_1009,John Doe,2023-09-01,97.61,63.0,95.0,No,Pending
18,STU_1153,John Doe,2023-09-01,76.86,84.0,92.0,Yes,Pending
32,STU_1112,John Doe,2023-09-01,75.58,56.0,100.0,Yes,Pending
34,STU_1124,John Doe,2023-09-01,81.53,51.0,73.0,No,Paid
41,STU_1183,John Doe,2023-09-01,96.32,83.0,88.0,No,Paid
43,STU_1093,John Doe,2023-09-01,71.09,84.0,71.0,Yes,Paid
60,STU_1068,John Doe,2023-09-01,82.36,75.0,57.0,No,Paid
72,STU_1035,John Doe,2023-09-01,84.27,94.0,68.0,No,Paid
123,STU_1156,John Doe,2023-09-01,89.96,80.0,42.0,Yes,Paid
128,STU_1070,John Doe,2023-09-01,92.16,73.0,49.0,Yes,Paid
129,STU_1181,John Doe,2023-09-01,97.16,76.0,80.0,No,Paid
131,STU_1044,John Doe,2023-09-01,71.35,88.0,58.0,Yes,Pending
136,STU_1161,John Doe,2023-09-01,98.29,95.0,60.0,No,Paid
190,STU_1129,John Doe,2023-09-01,70.92,57.0,51.0,Yes,Pending
194,STU_1001,John Doe,2023-09-01,64.63,61.0,70.0,Yes,Paid
199,STU_1103,John Doe,2023-09-01,66.03,67.0,56.0,Yes,Paid
205,STU_1121,John Doe,2023-09-01,75.60,100.0,88.0,No,Paid
207,STU_1020,John Doe,2023-09-01,86.68,81.0,88.0,Yes,Paid

In [73]:
# filtering those who have passed the preparation test
passed_prep = df[df['Passed_Prep_Course']=="Yes"]
print(len(passed_prep))

98

### Sorting

In [76]:
# sorting the final exam score to see the top scores
df.sort_values('Final_Exam_Score', ascending=False).head(10)

,Student_ID,Full Name,Enrollment_Date,Attendance_Rate,Midterm_Score,Final_Exam_Score,Passed_Prep_Course,Payment_Status
56,STU_1019,Charlie Brown,2023-09-01,80.28,73.0,100.0,Yes,Pending
32,STU_1112,John Doe,2023-09-01,75.58,56.0,100.0,Yes,Pending
162,STU_1089,Bob Marley,2023-09-01,94.46,70.0,100.0,Yes,Paid
198,STU_1151,Jane Smith,2023-09-01,71.13,75.0,100.0,Yes,Paid
165,STU_1059,Jane Smith,2023-09-01,83.03,91.0,99.0,Yes,Paid
78,STU_1051,Charlie Brown,2023-09-01,92.26,41.0,99.0,No,Paid
14,STU_1067,Emma Watson,2023-09-01,95.42,57.0,98.0,Yes,Paid
154,STU_1080,Sarah-Jane O'Connor,2023-09-01,72.69,55.0,98.0,No,Paid
85,STU_1127,Charlie Brown,2023-09-01,95.91,87.0,98.0,No,Paid
108,STU_1006,Jane Smith,2023-09-01,80.80,70.0,98.0,No,Pending

In [78]:
# sorting the attendance column to see the worst attendance
df.sort_values('Attendance_Rate', ascending=True).head(10)

,Student_ID,Full Name,Enrollment_Date,Attendance_Rate,Midterm_Score,Final_Exam_Score,Passed_Prep_Course,Payment_Status
94,STU_1115,Jane Smith,2023-09-01,60.78,86.0,83.0,No,Pending
127,STU_1163,Jane Smith,2023-09-01,61.24,76.0,89.0,No,Paid
49,STU_1162,Emma Watson,2023-09-01,61.61,40.0,47.0,Yes,Paid
113,STU_1004,Bob Marley,2023-09-01,61.78,66.0,64.0,Yes,Paid
148,STU_1053,Emma Watson,2023-09-01,61.85,94.0,90.0,Yes,Paid
192,STU_1157,Jane Smith,2023-09-01,62.08,70.0,69.0,No,Paid
157,STU_1110,Alice Johnson,2023-09-01,62.49,57.0,76.0,No,Pending
187,STU_1160,Jane Smith,2023-09-01,62.74,46.0,56.0,Yes,Pending
152,STU_1199,Jane Smith,2023-09-01,62.76,90.0,91.0,No,Pending
214,STU_1102,Charlie Brown,2023-09-01,63.22,62.0,78.0,No,Pending

In [80]:
df.sort_values(['Attendance_Rate', 'Final_Exam_Score'], ascending=[False, False]).head(15)

,Student_ID,Full Name,Enrollment_Date,Attendance_Rate,Midterm_Score,Final_Exam_Score,Passed_Prep_Course,Payment_Status
125,STU_1000,Jane Smith,2023-09-01,99.37,81.0,79.0,No,Paid
176,STU_1054,Alice Johnson,2023-09-01,99.36,60.0,90.0,No,Paid
46,STU_1137,Sarah-Jane O'Connor,2023-09-01,99.23,93.0,62.0,No,Paid
15,STU_1175,Jane Smith,2023-09-01,98.55,47.0,52.0,No,Paid
82,STU_1041,Emma Watson,2023-09-01,98.39,96.0,54.0,No,Paid
136,STU_1161,John Doe,2023-09-01,98.29,95.0,60.0,No,Paid
10,STU_1158,John Doe,2023-09-01,98.08,88.0,45.0,Yes,Pending
183,STU_1048,Bob Marley,2023-09-01,98.08,82.0,44.0,Yes,Paid
50,STU_1152,Emma Watson,2023-09-01,98.05,58.0,65.0,No,Pending
164,STU_1013,Bob Marley,2023-09-01,97.95,69.0,76.0,Yes,Paid
107,STU_1170,Bob Marley,2023-09-01,97.91,43.0,95.0,No,Pending
119,STU_1114,Alice Johnson,2023-09-01,97.84,47.0,88.0,No,Pending
103,STU_1119,Emma Watson,2023-09-01,97.71,87.0,42.0,No,Paid
20,STU_1185,Emma Watson,2023-09-01,97.66,49.0,53.0,No,Paid
13,STU_1009,John Doe,2023-09-01,97.61,63.0,95.0,No,Pending

In [85]:
df.sort_index()

,Student_ID,Full Name,Enrollment_Date,Attendance_Rate,Midterm_Score,Final_Exam_Score,Passed_Prep_Course,Payment_Status
0,STU_1010,John Doe,2023-09-01,89.48,80.0,77.0,Yes,Paid
2,STU_1138,Alice Johnson,2023-09-01,81.36,52.0,66.0,No,Pending
3,STU_1176,Michael Jordan,2023-09-01,88.73,92.0,73.0,No,Paid
5,STU_1111,Sarah-Jane O'Connor,2023-09-01,93.32,59.0,77.0,Yes,Pending
6,STU_1168,Alice Johnson,2023-09-01,78.94,70.0,40.0,No,Paid
...,...,...,...,...,...,...,...,...
209,STU_1071,Emma Watson,2023-09-01,82.36,100.0,44.0,No,Pending
210,STU_1106,Emma Watson,2023-09-01,68.56,61.0,54.0,Yes,Pending
212,STU_1092,Jane Smith,2023-09-01,93.59,65.0,74.0,Yes,Paid
213,STU_1179,Michael Jordan,2023-09-01,72.44,71.0,88.0,Yes,Paid
214,STU_1102,Charlie Brown,2023-09-01,63.22,62.0,78.0,No,Pending

 ### Grouping

In [86]:
# Average scores grouped by whether the student passed the prep course
df.groupby('Passed_Prep_Course')[['Midterm_Score', 'Final_Exam_Score', 'Attendance_Rate']].mean()

                    Midterm_Score  Final_Exam_Score  Attendance_Rate
Passed_Prep_Course
No                      69.529412         70.323529        83.301176
Yes                     70.244898         69.642857        80.673061

In [87]:
# Average scores grouped by payment status
df.groupby('Payment_Status')[['Midterm_Score', 'Final_Exam_Score', 'Attendance_Rate']].mean()

                Midterm_Score  Final_Exam_Score  Attendance_Rate
Payment_Status
Paid                70.587786         69.412214        82.643053
Pending             68.536232         71.086957        80.817971

In [90]:
# Count of students in each group
df.groupby('Passed_Prep_Course').size()

Passed_Prep_Course
No     102
Yes     98
dtype: int64

In [91]:
# Multiple aggregations at once using .agg()
df.groupby('Passed_Prep_Course').agg(
    avg_final=('Final_Exam_Score', 'mean'),
    max_final=('Final_Exam_Score', 'max'),
    min_final=('Final_Exam_Score', 'min'),
    avg_attendance=('Attendance_Rate', 'mean'),
    student_count=('Student_ID', 'count')
).round(2)

,avg_final,max_final,min_final,avg_attendance,student_count
Passed_Prep_Course,,,,,
No,70.32,99.0,40.0,83.30,102
Yes,69.64,100.0,42.0,80.67,98

In [92]:
# Grouping by two columns at once (prep course AND payment status)
df.groupby(['Passed_Prep_Course', 'Payment_Status'])['Final_Exam_Score'].mean().round(2)

Passed_Prep_Course  Payment_Status
No                  Paid              69.86
                    Pending           71.17
Yes                 Paid              68.95
                    Pending           71.00
Name: Final_Exam_Score, dtype: float64

### Statistical analysis

In [93]:
# Correlation between the numeric columns:
df[['Attendance_Rate', 'Midterm_Score', 'Final_Exam_Score']].corr()

                  Attendance_Rate  Midterm_Score  Final_Exam_Score
Attendance_Rate          1.000000      -0.021944         -0.011289
Midterm_Score           -0.021944       1.000000         -0.001929
Final_Exam_Score        -0.011289      -0.001929          1.000000

In [94]:
# Add a derived column: overall average score, and a Pass/Fail flag
df['Overall_Avg'] = df[['Midterm_Score', 'Final_Exam_Score']].mean(axis=1).round(2)
df['Result'] = np.where(df['Overall_Avg'] >= 50, 'Pass', 'Fail')
df['Result'].value_counts()

Result
Pass    191
Fail      9
Name: count, dtype: int64